name: amplify_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.0.0
  aws_signature_v4:
    path: ../aws_signature_v4

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  pedantic: ^1.10.0
  test: ^1.16.0
