name: aws_signature_v4
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.2
  aws_common:
    path: ../aws_common
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  meta: ^1.0.0

dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  lints: ^1.0.0
  path: ^1.8.0
  test: ^1.16.0
