name: aws_cognito
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_common:
    path: ../aws_common
  aws_signature_v4:
    path: ../aws_signature_v4
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
  lints: ^1.0.0
  test: ^1.16.0
