name: smithy
description: Smithy client runtime for Dart
version: 0.1.0

environment:
  sdk: '>=2.15.0-0 <3.0.0'

dependencies:
  aws_common:
    path: ../../../pocs/aws_common
  collection: ^1.15.0
  fixnum: ^1.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^4.3.0
  meta: ^1.7.0
  xml: ^5.3.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^1.0.0
  test: ^1.16.0
